apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: mapper-display-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-mapper
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display