apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: pingsource-sequence
spec:
  schedule: "*/1 * * * *"
  jsonData: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: mapper-sequence