apiVersion: sources.knative.dev/v1alpha2
kind: ContainerSource
metadata:
  name: producer-eventsource
spec:
  template:
    spec:
      containers:
        - image: docker.io/alitari/ce-go-template-periodic-producer
          name: ce-go-template-producer
          # env:
          #   - name: CE_TEMPLATE
          #     value: '$PRODUCER_CE_TEMPLATE'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
