apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: producer-display-binding
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: event-producer

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display