apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: mapper-sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: event-mapper
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: event-display
