@startuml ce-go-template-mapper
EventSource -> "ce-go-template-mapper": cloud event
hnote over "ce-go-template-mapper" : transformation based on CE_TEMPLATE
"ce-go-template-mapper" --> EventSource: transformed cloud event in respoonse
note right: if no `K_SINK`
"ce-go-template-mapper" -> EventSink: transformed cloud event
note left: if `K_SINK` defined

@enduml