name: PublishImages

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: alitari
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
